create table user_profile (
    id bigint generated by default as identity primary key,
    auth_user_id uuid,
    name varchar(150) not null,
    email varchar(255) not null,
    active boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_user_profile_email unique (email),
    constraint uk_user_profile_auth_user_id unique (auth_user_id)
);

create index idx_user_profile_active on user_profile (active);

create table role (
    id bigint generated by default as identity primary key,
    code varchar(60) not null,
    name varchar(100) not null,
    sort_order integer not null,
    active boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_role_code unique (code),
    constraint uk_role_sort_order unique (sort_order),
    constraint chk_role_sort_order_positive check (sort_order > 0)
);

create index idx_role_active on role (active);

create table user_profile_role (
    id bigint generated by default as identity primary key,
    user_profile_id bigint not null,
    role_id bigint not null,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint fk_user_profile_role_user_profile foreign key (user_profile_id) references user_profile (id),
    constraint fk_user_profile_role_role foreign key (role_id) references role (id)
);

create unique index ux_user_profile_role_no_duplicate_role_assignment
    on user_profile_role (user_profile_id, role_id)
    where deleted_at is null;

create index idx_user_profile_role_user_profile_id on user_profile_role (user_profile_id);
create index idx_user_profile_role_role_id on user_profile_role (role_id);

create table customer (
    id bigint generated by default as identity primary key,
    code varchar(50) not null,
    user_profile_id bigint not null,
    name varchar(150) not null,
    tax_number varchar(30),
    phone varchar(30),
    address_line varchar(255),
    city varchar(100),
    postal_code varchar(20),
    active boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_customer_code unique (code),
    constraint uk_customer_user_profile_id unique (user_profile_id),
    constraint fk_customer_user_profile foreign key (user_profile_id) references user_profile (id)
);

create index idx_customer_active on customer (active);

create table employee (
    id bigint generated by default as identity primary key,
    code varchar(50) not null,
    user_profile_id bigint not null,
    name varchar(150) not null,
    job_title varchar(100),
    active boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_employee_code unique (code),
    constraint uk_employee_user_profile_id unique (user_profile_id),
    constraint fk_employee_user_profile foreign key (user_profile_id) references user_profile (id)
);

create index idx_employee_active on employee (active);
