create table part_type (
    id bigint generated by default as identity primary key,
    code varchar(60) not null,
    name varchar(100) not null,
    sort_order integer not null,
    active boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_part_type_code unique (code),
    constraint uk_part_type_sort_order unique (sort_order),
    constraint chk_part_type_sort_order_positive check (sort_order > 0)
);

create index idx_part_type_active on part_type (active);

create table raw_material_order_status (
    id bigint generated by default as identity primary key,
    code varchar(60) not null,
    name varchar(100) not null,
    sort_order integer not null,
    active boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_raw_material_order_status_code unique (code),
    constraint uk_raw_material_order_status_sort_order unique (sort_order),
    constraint chk_raw_material_order_status_sort_order_positive check (sort_order > 0)
);

create index idx_raw_material_order_status_active on raw_material_order_status (active);

create table stock_status (
    id bigint generated by default as identity primary key,
    code varchar(60) not null,
    name varchar(100) not null,
    sort_order integer not null,
    active boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_stock_status_code unique (code),
    constraint uk_stock_status_sort_order unique (sort_order),
    constraint chk_stock_status_sort_order_positive check (sort_order > 0)
);

create index idx_stock_status_active on stock_status (active);

create table stock_reservation_status (
    id bigint generated by default as identity primary key,
    code varchar(60) not null,
    name varchar(100) not null,
    sort_order integer not null,
    active boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_stock_reservation_status_code unique (code),
    constraint uk_stock_reservation_status_sort_order unique (sort_order),
    constraint chk_stock_reservation_status_sort_order_positive check (sort_order > 0)
);

create index idx_stock_reservation_status_active on stock_reservation_status (active);

create table customer_order_status (
    id bigint generated by default as identity primary key,
    code varchar(60) not null,
    name varchar(100) not null,
    sort_order integer not null,
    active boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_customer_order_status_code unique (code),
    constraint uk_customer_order_status_sort_order unique (sort_order),
    constraint chk_customer_order_status_sort_order_positive check (sort_order > 0)
);

create index idx_customer_order_status_active on customer_order_status (active);

create table manufacturing_order_status (
    id bigint generated by default as identity primary key,
    code varchar(60) not null,
    name varchar(100) not null,
    sort_order integer not null,
    active boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_manufacturing_order_status_code unique (code),
    constraint uk_manufacturing_order_status_sort_order unique (sort_order),
    constraint chk_manufacturing_order_status_sort_order_positive check (sort_order > 0)
);

create index idx_manufacturing_order_status_active on manufacturing_order_status (active);

create table quality_record_type (
    id bigint generated by default as identity primary key,
    code varchar(60) not null,
    name varchar(100) not null,
    sort_order integer not null,
    active boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_quality_record_type_code unique (code),
    constraint uk_quality_record_type_sort_order unique (sort_order),
    constraint chk_quality_record_type_sort_order_positive check (sort_order > 0)
);

create index idx_quality_record_type_active on quality_record_type (active);
