create table raw_material (
    id bigint generated by default as identity primary key,
    code varchar(80) not null,
    name varchar(150) not null,
    default_unit varchar(20) not null,
    active boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_raw_material_code unique (code)
);

create index idx_raw_material_active on raw_material (active);

create table part (
    id bigint generated by default as identity primary key,
    code varchar(80) not null,
    name varchar(150) not null,
    description text,
    part_type_id bigint not null,
    active boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_part_code unique (code),
    constraint fk_part_part_type foreign key (part_type_id) references part_type (id)
);

create index idx_part_part_type_id on part (part_type_id);
create index idx_part_active on part (active);
