create table bill_of_material_item (
    id bigint generated by default as identity primary key,
    parent_part_id bigint not null,
    component_part_id bigint not null,
    quantity numeric(14,3) not null,
    active boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint fk_bill_of_material_item_parent_part foreign key (parent_part_id) references part (id),
    constraint fk_bill_of_material_item_component_part foreign key (component_part_id) references part (id),
    constraint chk_bill_of_material_item_quantity_positive check (quantity > 0),
    constraint chk_bill_of_material_item_different_parts check (parent_part_id <> component_part_id)
);

create unique index ux_bill_of_material_item_no_duplicate_component
    on bill_of_material_item (parent_part_id, component_part_id)
    where deleted_at is null;

create index idx_bill_of_material_item_parent_part_id on bill_of_material_item (parent_part_id);
create index idx_bill_of_material_item_component_part_id on bill_of_material_item (component_part_id);
create index idx_bill_of_material_item_active on bill_of_material_item (active);

create table part_raw_material_requirement (
    id bigint generated by default as identity primary key,
    part_id bigint not null,
    raw_material_id bigint not null,
    quantity numeric(14,3) not null,
    unit varchar(20) not null,
    waste_percentage numeric(5,2) not null default 0,
    active boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint fk_part_raw_material_requirement_part foreign key (part_id) references part (id),
    constraint fk_part_raw_material_requirement_raw_material foreign key (raw_material_id) references raw_material (id),
    constraint chk_part_raw_material_requirement_quantity_positive check (quantity > 0),
    constraint chk_part_raw_material_requirement_waste_not_negative check (waste_percentage >= 0)
);

create unique index ux_part_raw_material_requirement_no_duplicate_raw_material
    on part_raw_material_requirement (part_id, raw_material_id)
    where deleted_at is null;

create index idx_part_raw_material_requirement_part_id on part_raw_material_requirement (part_id);
create index idx_part_raw_material_requirement_raw_material_id on part_raw_material_requirement (raw_material_id);
create index idx_part_raw_material_requirement_active on part_raw_material_requirement (active);
