create table raw_material_order (
    id bigint generated by default as identity primary key,
    code varchar(80) not null,
    status_id bigint not null,
    order_date date not null,
    confirmed_at timestamp,
    notes text,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_raw_material_order_code unique (code),
    constraint fk_raw_material_order_status foreign key (status_id) references raw_material_order_status (id)
);

create index idx_raw_material_order_status_id on raw_material_order (status_id);
create index idx_raw_material_order_order_date on raw_material_order (order_date);

create table raw_material_order_line (
    id bigint generated by default as identity primary key,
    raw_material_order_id bigint not null,
    raw_material_id bigint not null,
    quantity numeric(14,3) not null,
    unit varchar(20) not null,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint fk_raw_material_order_line_order foreign key (raw_material_order_id) references raw_material_order (id),
    constraint fk_raw_material_order_line_raw_material foreign key (raw_material_id) references raw_material (id),
    constraint chk_raw_material_order_line_quantity_positive check (quantity > 0)
);

create unique index ux_raw_material_order_line_no_duplicate_raw_material
    on raw_material_order_line (raw_material_order_id, raw_material_id)
    where deleted_at is null;

create index idx_raw_material_order_line_order_id on raw_material_order_line (raw_material_order_id);
create index idx_raw_material_order_line_raw_material_id on raw_material_order_line (raw_material_id);

create table stock (
    id bigint generated by default as identity primary key,
    code varchar(80) not null,
    raw_material_id bigint not null,
    raw_material_order_id bigint,
    stock_status_id bigint not null,
    initial_quantity numeric(14,3) not null,
    available_quantity numeric(14,3) not null,
    unit varchar(20) not null,
    received_at timestamp,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_stock_code unique (code),
    constraint fk_stock_raw_material foreign key (raw_material_id) references raw_material (id),
    constraint fk_stock_raw_material_order foreign key (raw_material_order_id) references raw_material_order (id),
    constraint fk_stock_status foreign key (stock_status_id) references stock_status (id),
    constraint chk_stock_initial_quantity_positive check (initial_quantity > 0),
    constraint chk_stock_available_quantity_not_negative check (available_quantity >= 0),
    constraint chk_stock_available_quantity_not_above_initial check (available_quantity <= initial_quantity)
);

create index idx_stock_raw_material_id on stock (raw_material_id);
create index idx_stock_status_id on stock (stock_status_id);
create index idx_stock_raw_material_order_id on stock (raw_material_order_id);
create index idx_stock_raw_material_status on stock (raw_material_id, stock_status_id);
