create table customer_order (
    id bigint generated by default as identity primary key,
    code varchar(80) not null,
    customer_id bigint not null,
    status_id bigint not null,
    order_date date not null,
    validated_at timestamp,
    ready_for_production_at timestamp,
    shipped_at timestamp,
    notes text,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_customer_order_code unique (code),
    constraint fk_customer_order_customer foreign key (customer_id) references customer (id),
    constraint fk_customer_order_status foreign key (status_id) references customer_order_status (id)
);

create index idx_customer_order_customer_id on customer_order (customer_id);
create index idx_customer_order_status_id on customer_order (status_id);
create index idx_customer_order_order_date on customer_order (order_date);

create table customer_order_line (
    id bigint generated by default as identity primary key,
    customer_order_id bigint not null,
    part_id bigint not null,
    quantity numeric(14,3) not null,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint fk_customer_order_line_order foreign key (customer_order_id) references customer_order (id),
    constraint fk_customer_order_line_part foreign key (part_id) references part (id),
    constraint chk_customer_order_line_quantity_positive check (quantity > 0)
);

create unique index ux_customer_order_line_no_duplicate_part
    on customer_order_line (customer_order_id, part_id)
    where deleted_at is null;

create index idx_customer_order_line_order_id on customer_order_line (customer_order_id);
create index idx_customer_order_line_part_id on customer_order_line (part_id);
