create table manufacturing_order (
    id bigint generated by default as identity primary key,
    code varchar(80) not null,
    status_id bigint not null,
    customer_order_id bigint not null,
    customer_order_line_id bigint,
    part_id bigint not null,
    quantity numeric(14,3) not null,
    opened_at timestamp not null,
    completed_at timestamp,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_manufacturing_order_code unique (code),
    constraint fk_manufacturing_order_status foreign key (status_id) references manufacturing_order_status (id),
    constraint fk_manufacturing_order_customer_order foreign key (customer_order_id) references customer_order (id),
    constraint fk_manufacturing_order_customer_order_line foreign key (customer_order_line_id) references customer_order_line (id),
    constraint fk_manufacturing_order_part foreign key (part_id) references part (id),
    constraint chk_manufacturing_order_quantity_positive check (quantity > 0)
);

create index idx_manufacturing_order_status_id on manufacturing_order (status_id);
create index idx_manufacturing_order_customer_order_id on manufacturing_order (customer_order_id);
create index idx_manufacturing_order_customer_order_line_id on manufacturing_order (customer_order_line_id);
create index idx_manufacturing_order_part_id on manufacturing_order (part_id);

create table manufacturing_order_component (
    id bigint generated by default as identity primary key,
    parent_manufacturing_order_id bigint not null,
    component_manufacturing_order_id bigint not null,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint fk_manufacturing_order_component_parent foreign key (parent_manufacturing_order_id) references manufacturing_order (id),
    constraint fk_manufacturing_order_component_component foreign key (component_manufacturing_order_id) references manufacturing_order (id),
    constraint chk_manufacturing_order_component_different_orders check (parent_manufacturing_order_id <> component_manufacturing_order_id)
);

create unique index ux_manufacturing_order_component_no_duplicate_component_order
    on manufacturing_order_component (parent_manufacturing_order_id, component_manufacturing_order_id)
    where deleted_at is null;

create index idx_manufacturing_order_component_parent_id on manufacturing_order_component (parent_manufacturing_order_id);
create index idx_manufacturing_order_component_component_id on manufacturing_order_component (component_manufacturing_order_id);
