create table stock_reservation (
    id bigint generated by default as identity primary key,
    code varchar(80) not null,
    customer_order_id bigint not null,
    manufacturing_order_id bigint,
    raw_material_id bigint not null,
    stock_id bigint,
    status_id bigint not null,
    reserved_quantity numeric(14,3) not null,
    consumed_quantity numeric(14,3) not null default 0,
    unit varchar(20) not null,
    reserved_at timestamp not null,
    released_at timestamp,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_stock_reservation_code unique (code),
    constraint fk_stock_reservation_customer_order foreign key (customer_order_id) references customer_order (id),
    constraint fk_stock_reservation_manufacturing_order foreign key (manufacturing_order_id) references manufacturing_order (id),
    constraint fk_stock_reservation_raw_material foreign key (raw_material_id) references raw_material (id),
    constraint fk_stock_reservation_stock foreign key (stock_id) references stock (id),
    constraint fk_stock_reservation_status foreign key (status_id) references stock_reservation_status (id),
    constraint chk_stock_reservation_reserved_quantity_positive check (reserved_quantity > 0),
    constraint chk_stock_reservation_consumed_quantity_not_negative check (consumed_quantity >= 0),
    constraint chk_stock_reservation_consumed_not_above_reserved check (consumed_quantity <= reserved_quantity)
);

create index idx_stock_reservation_customer_order_id on stock_reservation (customer_order_id);
create index idx_stock_reservation_manufacturing_order_id on stock_reservation (manufacturing_order_id);
create index idx_stock_reservation_raw_material_id on stock_reservation (raw_material_id);
create index idx_stock_reservation_stock_id on stock_reservation (stock_id);
create index idx_stock_reservation_status_id on stock_reservation (status_id);
create index idx_stock_reservation_active_lookup on stock_reservation (raw_material_id, status_id);

create table stock_consumption (
    id bigint generated by default as identity primary key,
    code varchar(80) not null,
    manufacturing_order_id bigint not null,
    raw_material_id bigint not null,
    stock_id bigint not null,
    stock_reservation_id bigint,
    quantity numeric(14,3) not null,
    unit varchar(20) not null,
    consumed_at timestamp not null,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_stock_consumption_code unique (code),
    constraint fk_stock_consumption_manufacturing_order foreign key (manufacturing_order_id) references manufacturing_order (id),
    constraint fk_stock_consumption_raw_material foreign key (raw_material_id) references raw_material (id),
    constraint fk_stock_consumption_stock foreign key (stock_id) references stock (id),
    constraint fk_stock_consumption_stock_reservation foreign key (stock_reservation_id) references stock_reservation (id),
    constraint chk_stock_consumption_quantity_positive check (quantity > 0)
);

create index idx_stock_consumption_manufacturing_order_id on stock_consumption (manufacturing_order_id);
create index idx_stock_consumption_raw_material_id on stock_consumption (raw_material_id);
create index idx_stock_consumption_stock_id on stock_consumption (stock_id);
create index idx_stock_consumption_stock_reservation_id on stock_consumption (stock_reservation_id);
create index idx_stock_consumption_consumed_at on stock_consumption (consumed_at);
