create table rack (
    id bigint generated by default as identity primary key,
    code varchar(80) not null,
    name varchar(150) not null,
    active boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_rack_code unique (code)
);

create index idx_rack_active on rack (active);

create table rack_location (
    id bigint generated by default as identity primary key,
    rack_id bigint not null,
    manufacturing_order_id bigint not null,
    located_at timestamp not null,
    removed_at timestamp,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint fk_rack_location_rack foreign key (rack_id) references rack (id),
    constraint fk_rack_location_manufacturing_order foreign key (manufacturing_order_id) references manufacturing_order (id),
    constraint chk_rack_location_removed_after_located check (removed_at is null or removed_at >= located_at)
);

create index idx_rack_location_rack_id on rack_location (rack_id);
create index idx_rack_location_manufacturing_order_id on rack_location (manufacturing_order_id);

create table production_cart (
    id bigint generated by default as identity primary key,
    code varchar(80) not null,
    name varchar(150),
    active boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_production_cart_code unique (code)
);

create index idx_production_cart_active on production_cart (active);

create table sequencing (
    id bigint generated by default as identity primary key,
    production_cart_id bigint not null,
    manufacturing_order_id bigint not null,
    sequence_order integer not null,
    sequenced_at timestamp not null,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint fk_sequencing_production_cart foreign key (production_cart_id) references production_cart (id),
    constraint fk_sequencing_manufacturing_order foreign key (manufacturing_order_id) references manufacturing_order (id),
    constraint chk_sequencing_sequence_order_positive check (sequence_order > 0)
);

create unique index ux_sequencing_no_duplicate_order_in_cart
    on sequencing (production_cart_id, manufacturing_order_id)
    where deleted_at is null;

create unique index ux_sequencing_no_duplicate_sequence_in_cart
    on sequencing (production_cart_id, sequence_order)
    where deleted_at is null;

create index idx_sequencing_cart_id on sequencing (production_cart_id);
create index idx_sequencing_manufacturing_order_id on sequencing (manufacturing_order_id);

create table team (
    id bigint generated by default as identity primary key,
    code varchar(80) not null,
    name varchar(150) not null,
    active boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_team_code unique (code)
);

create index idx_team_active on team (active);

create table team_location (
    id bigint generated by default as identity primary key,
    team_id bigint not null,
    code varchar(80) not null,
    name varchar(150) not null,
    active boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_team_location_code unique (code),
    constraint fk_team_location_team foreign key (team_id) references team (id)
);

create index idx_team_location_team_id on team_location (team_id);
create index idx_team_location_active on team_location (active);

create table production_plan (
    id bigint generated by default as identity primary key,
    manufacturing_order_id bigint not null,
    team_id bigint,
    team_location_id bigint,
    planned_start_at timestamp,
    planned_end_at timestamp,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint fk_production_plan_manufacturing_order foreign key (manufacturing_order_id) references manufacturing_order (id),
    constraint fk_production_plan_team foreign key (team_id) references team (id),
    constraint fk_production_plan_team_location foreign key (team_location_id) references team_location (id),
    constraint chk_production_plan_planned_dates_order check (planned_end_at is null or planned_start_at is null or planned_end_at >= planned_start_at)
);

create index idx_production_plan_manufacturing_order_id on production_plan (manufacturing_order_id);
create index idx_production_plan_team_id on production_plan (team_id);
create index idx_production_plan_team_location_id on production_plan (team_location_id);
create index idx_production_plan_planned_start_at on production_plan (planned_start_at);

create table label (
    id bigint generated by default as identity primary key,
    code varchar(100) not null,
    manufacturing_order_id bigint not null,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_label_code unique (code),
    constraint fk_label_manufacturing_order foreign key (manufacturing_order_id) references manufacturing_order (id)
);

create index idx_label_manufacturing_order_id on label (manufacturing_order_id);

create table quality_record (
    id bigint generated by default as identity primary key,
    code varchar(80) not null,
    quality_record_type_id bigint not null,
    manufacturing_order_id bigint not null,
    label_id bigint,
    quantity numeric(14,3) not null,
    notes text,
    recorded_at timestamp not null,
    created_at timestamp not null default now(),
    updated_at timestamp,
    deleted_at timestamp,
    constraint uk_quality_record_code unique (code),
    constraint fk_quality_record_type foreign key (quality_record_type_id) references quality_record_type (id),
    constraint fk_quality_record_manufacturing_order foreign key (manufacturing_order_id) references manufacturing_order (id),
    constraint fk_quality_record_label foreign key (label_id) references label (id),
    constraint chk_quality_record_quantity_positive check (quantity > 0)
);

create index idx_quality_record_type_id on quality_record (quality_record_type_id);
create index idx_quality_record_manufacturing_order_id on quality_record (manufacturing_order_id);
create index idx_quality_record_label_id on quality_record (label_id);
create index idx_quality_record_recorded_at on quality_record (recorded_at);
